name: Niada Cradle Photography
favicon: null
layout_spectrum: 0.21993
typography_spectrum: 0.7692809605505317
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#cfc1a7'
    - '#f7f1e6'
    - '#918973'
    - '#4c4333'
    - '#746e59'
  brandStrength: 0.1875
  lightness: 0.8891650196164846
  saturation: 0.6617487077601254
  rhythmicContrast: 0.28075336501933634
purpose: []
